name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  verify-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '2.3.3'

      - name: Update Dependencies
        run: |
          # Update deno.lock to match CI environment
          deno cache --reload --lock-write mod.ts

      - name: Get tag version
        id: get_tag
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Verify version matches deno.json
        run: |
          DENO_VERSION=$(deno eval "const config = JSON.parse(await Deno.readTextFile('deno.json')); console.log(config.version);")
          TAG_VERSION="${{ steps.get_tag.outputs.VERSION }}"
          if [ "$DENO_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version mismatch between tag ($TAG_VERSION) and deno.json ($DENO_VERSION)"
            exit 1
          fi

      - name: Type Check
        run: |
          deno check mod.ts
          deno check "src/**/*.ts"
          deno check "tests/**/*.ts"

      - name: Run tests
        run: deno test --allow-env --allow-write --allow-read

      - name: Publish to JSR
        run: |
          # Check if deno.lock has changed
          if git diff --exit-code deno.lock; then
            # No changes, proceed with publish
            deno publish
          else
            # deno.lock changed, use --allow-dirty only for this specific case
            echo "Warning: deno.lock has been updated in CI environment"
            deno publish --allow-dirty
          fi
        env:
          DENO_JSON_PATH: './deno.json'
