name: Publish to JSR

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Rebuild deno.lock
        run: deno cache --reload mod.ts

      - name: Run tests
        run: deno test --check

      - name: Run linter
        run: deno lint

      - name: Publish to JSR
        run: deno publish
        env:
          DENO_AUTH_TOKEN: ${{ secrets.DENO_AUTH_TOKEN }} 