name: Version Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'deno.json'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '2.1.9'

      - name: Get current version
        id: current
        run: |
          CURRENT_VERSION=$(deno eval "const config = JSON.parse(await Deno.readTextFile('deno.json')); console.log(config.version);")
          echo "VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

      - name: Get latest version from JSR
        id: latest
        run: |
          LATEST_VERSION=$(curl -s https://jsr.io/@tettuan/breakdownparams/versions | grep -o '0\.[0-9]\+\.[0-9]\+' | head -n 1)
          echo "VERSION=${LATEST_VERSION}" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          CURRENT="${{ steps.current.outputs.VERSION }}"
          LATEST="${{ steps.latest.outputs.VERSION }}"
          if [ "$(printf '%s\n%s\n' "$LATEST" "$CURRENT" | sort -V | head -n1)" = "$CURRENT" ]; then
            echo "Error: New version ($CURRENT) must be greater than the latest version ($LATEST)"
            exit 1
          fi
